version: "0.2"
ignorePaths:
  - .gitignore
  - requirements.txt
  - alembic*
allowCompoundWords: true
dictionaries:
  - python
words:
  - apscheduler
  - clsname
  - grnd
  - isort
  - kwdefaults
  - Misha
  - mypy
  - ondelete
  - onupdate
  - psycopg
  - pydantic
  - pytest
  - sqlalchemy
  - testdb
  - uvicorn
  - vbrn
  - venv
  - vybornyy
ignoreWords: []
import: []
enableFiletypes:
  - dockercompose
  - ini
  - makefile
  - markdown
  - toml
